swagger: '2.0'
schemes:
  - https
host: api.sandbox.paypal.com
basePath: /v1/vault
info:
  contact:
    name: PayPal Vault API
    url: 'https://developer.paypal.com/docs/api/vault/'
  description: >-
    Merchants can use the Vault API to securely store customer credit cards in
    the PayPal vault rather than on your server. When you use the API to store a
    customer credit card, the API returns the ID of the vaulted card. To take a
    payment with the vaulted card, you specify the ID of the vaulted card
    instead of credit card details. For information, see the Vault overview.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://www.paypal.com/us/webapps/mpp/ua/xdeveloper-full'
  title: PayPal Vault API
  version: v1
externalDocs:
  url: 'https://developer.paypal.com/docs/api/'
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://www.sandbox.paypal.com/signin/authorize'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://uri.paypal.com/services/vault': Vault
      openid: Login
    tokenUrl: 'https://api.sandbox.paypal.com/v1/oauth2/token'
    type: oauth2
  Oauth2c:
    description: Oauth 2.0 accessCode authentication
    flow: application
    scopes:
      'https://uri.paypal.com/services/vault': Vault
      openid: Login
    tokenUrl: 'https://api.sandbox.paypal.com/v1/oauth2/token'
    type: oauth2
tags:
  - name: vault
paths:
  /credit-cards:
    post:
      description: >-
        Stores credit card details in the PayPal vault. A successful request
        returns the HTTP 201 Created status code and a JSON response body that
        shows credit card details, including the ID of the vaulted card. To use
        the vaulted card to make a payment, specify this ID as the
        credit_card_id in a credit_card_token object. If you include a payer_id
        when you store the credit card, you must also include that ID as the
        external_customer_id in the credit_card_token object. You can also use
        the ID of the vaulted credit card to show details for, update, or delete
        the vaulted card.
      operationId: storeCreditCard
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: storeRequest
          in: body
          description: >-
            Object containing credit card details for the request to store a
            credit card.
          required: true
          schema:
            $ref: '#/definitions/StoreRequest'
      responses:
        '201':
          description: Client request successful
          schema:
            $ref: '#/definitions/CreditCard'
      security:
        - Oauth2c:
            - 'https://uri.paypal.com/services/vault'
      tags:
        - vault
    get:
      description: >-
        Lists vaulted credit cards. To filter the cards in the response, specify
        one or more optional query parameters. A successful request returns the
        HTTP 200 OK status code and a JSON response body that includes an array
        of vaulted cards. Each item in the array shows card details.
      operationId: listCreditCards
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: page_size
          in: query
          description: >-
            The number of vaulted credit cards to list in the response beginning
            with the specified page.
          type: integer
          format: int64
        - name: page
          in: query
          description: A zero-relative index of the list of vaulted credit cards.
          type: integer
          format: int64
        - name: start_time
          in: query
          description: >-
            Filters the vaulted credit cards in the response to those created on
            or after this date and time and on or before the end_time value.
            Both values are in Internet date and time format. For example,
            2017-11-05T13:15:30Z.
          type: string
        - name: end_time
          in: query
          description: >-
            Filters the vaulted credit cards in the response to those created on
            or after the start_time date and time and on or before this value.
            Both values are in Internet date and time format. For example,
            2017-11-05T13:15:30Z.
          type: string
        - name: sort_order
          in: query
          description: >-
            Sorts the vaulted credit cards in the response in ascending or
            descending order. Value is asc for ascending order or desc for
            descending order.
          type: string
        - name: sort_by
          in: query
          description: >-
            Sorts the vaulted credit cards in the response by either create_time
            or update_time.
          type: string
        - name: merchant_id
          in: query
          description: >-
            Filters the vaulted credit cards in the response to those associated
            with this merchant ID. This value is a user-provided unique ID for
            the merchant who holds the card. Note: This parameter is not related
            to the PayPal merchant ID.
          type: string
        - name: external_card_id
          in: query
          description: >-
            Filters the vaulted credit cards in the response to those associated
            with this facilitator-provided ID of the bank account.
          type: string
        - name: external_customer_id
          in: query
          description: >-
            Filters the vaulted credit cards in the response to those associated
            with this externally-provided customer ID.
          type: string
        - name: total_required
          in: query
          description: >-
            Indicates whether the response returns the total_items and
            total_pages values. Default is true. Set to false to omit these
            values from the response.
          type: boolean
      responses:
        '200':
          description: Client request successful
          schema:
            $ref: '#/definitions/CreditCardList'
      security:
        - Oauth2c:
            - 'https://uri.paypal.com/services/vault'
      tags:
        - vault
  '/credit-cards/{credit_card_id}':
    get:
      description: >-
        Shows details for a vaulted credit card, by ID. A successful request
        returns the HTTP 200 OK status code and a JSON response body with card
        details.
      operationId: showCreditCardDetails
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: credit_card_id
          in: path
          description: >-
            The ID of the vaulted credit card for which to show details. This ID
            is returned when you store the credit card in the PayPal vault.
          required: true
          type: string
      responses:
        '200':
          description: Client request successful
          schema:
            $ref: '#/definitions/CreditCard'
      security:
        - Oauth2c:
            - 'https://uri.paypal.com/services/vault'
      tags:
        - vault
    patch:
      description: >-
        Updates information for a vaulted credit card, by ID. In the JSON
        request body, specify the values to update. A successful request returns
        the HTTP 200 OK status code and a JSON response body that shows card
        details.
      operationId: updateCreditCard
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: credit_card_id
          in: path
          description: >-
            The ID of the vaulted credit card for which to show details. This ID
            is returned when you store the credit card in the PayPal vault.
          required: true
          type: string
        - name: updateRequest
          in: body
          description: >-
            A JSON patch object that you can use to apply partial updates to
            resources.
          required: true
          schema:
            $ref: '#/definitions/JsonPatchRequest'
      responses:
        '200':
          description: Client request successful
          schema:
            $ref: '#/definitions/CreditCard'
      security:
        - Oauth2c:
            - 'https://uri.paypal.com/services/vault'
      tags:
        - vault
    delete:
      description: 'Deletes a vaulted credit card, by ID.'
      operationId: deleteCreditCard
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - name: credit_card_id
          in: path
          description: >-
            The ID of the vaulted credit card for which to show details. This ID
            is returned when you store the credit card in the PayPal vault.
          required: true
          type: string
      responses:
        '204':
          description: Client request successful
      security:
        - Oauth2c:
            - 'https://uri.paypal.com/services/vault'
      tags:
        - vault
definitions:
  Address:
    properties:
      line1:
        type: string
        description: 'The first line of the address. For example, number, street, and so on.'
      line2:
        type: string
        description: >-
          Optional. The second line of the address. For example, suite, apt
          number, and so on.
      city:
        type: string
        description: The city name.
      country_code:
        type: string
        description: >-
          The two-letter code for a US state. Use the equivalent for other
          countries.
      postal_code:
        type: string
        description: >-
          The postal code, which is the zip code or equivalent. Typically
          required for countries with postal codes. For countries that have
          postal codes or an equivalent, see Postal code.
      state:
        type: string
        description: >-
          The two-character ISO 3166-1 code that identifies the country or
          region. Note: The country code for Great Britain is GB and not UK as
          is used in that country's top-level domain names. Use the C2 country
          code for CHINA WORLDWIDE (for CUP, bank card, and cross-border
          transactions).
      phone:
        type: string
        description: >-
          A phone number. Must be represented in its canonical international
          format, as defined by the E.164 numbering plan.
    type: object
  CreditCard:
    properties:
      id:
        type: string
        description: >-
          The ID of the vaulted credit card. You can use this ID to fund a
          payment.
      number:
        type: string
        description: >-
          The credit card number. Valid value is a string of numeric characters
          with no spaces or punctuation. Must conform to modulo and the length
          required by its credit card type. Redacted in responses.
      type:
        type: string
        description: The credit card type.
        enum:
          - visa
          - mastercard
          - amex
          - discover
          - maestro
      expire_month:
        type: integer
        format: int64
        description: >-
          The one- to two-digit month when the card expires, with no leading
          zero. For example, 1 or 12.
      expire_year:
        type: integer
        format: int64
        description: 'The four-digit year when the card expires. For example, 2017.'
      first_name:
        type: string
        description: >-
          The first name of the credit card holder. Maximum length is 25
          characters.
      last_name:
        type: string
        description: The last name of the credit card holder.
      billing_address:
        $ref: '#/definitions/Address'
      external_customer_id:
        type: string
        description: >-
          The externally-provided ID of the customer for whom to list credit
          cards.
      merchant_id:
        type: string
        description: The ID of the merchant for whom to list credit cards.
      payer_id:
        type: string
        description: >-
          A unique ID that you can assign and track when you vault a credit card
          or use a vaulted credit card to make a payment. This ID can help to
          avoid unintentional use or misuse of credit cards. Can be any value,
          such as a UUID, user name, or email address. This is being deprecated
          in favor of the external_customer_id property.
      external_card_id:
        type: string
        description: The externally-provided ID of the credit card.
      state:
        type: string
        description: The state of the credit card funding instrument.
        enum:
          - expired
          - ok
      create_time:
        type: string
        description: >-
          The date and time when the vaulted credit card was created, in
          Internet date and time format. For example, 2017-11-05T13:15:30Z.
      update_time:
        type: string
        description: >-
          The date and time when the vaulted credit card was updated, in
          Internet date and time format. For example, 2017-11-05T13:15:30Z.
      valid_until:
        type: string
        description: >-
          The date and time when the credit card becomes unusable from the
          vault, in Internet date and time format. The valid_until parameter is
          not the same as the expiration month and year. The expiration month
          and year might be later than the valid_until date. For example, the
          card expires in November 2019 but the valid_until date is October
          17th, 2019.
      links:
        type: array
        description: HATEOAS links related to this call.
        items:
          $ref: '#/definitions/Link'
    type: object
  StoreRequest:
    required:
      - number
      - type
      - expire_month
      - expire_year
    properties:
      number:
        type: string
        description: >-
          The credit card number. Valid value is a string of numeric characters
          with no spaces or punctuation. Must conform to modulo and the length
          required by its credit card type. Redacted in responses.
      type:
        type: string
        description: The credit card type.
        enum:
          - visa
          - mastercard
          - amex
          - discover
          - maestro
      expire_month:
        type: integer
        format: int64
        description: >-
          The one- to two-digit month when the card expires, with no leading
          zero. For example, 1 or 12.
      expire_year:
        type: integer
        format: int64
        description: 'The four-digit year when the card expires. For example, 2017.'
      first_name:
        type: string
        description: >-
          The first name of the credit card holder. Maximum length is 25
          characters.
      last_name:
        type: string
        description: The last name of the credit card holder.
      billing_address:
        $ref: '#/definitions/Address'
      external_customer_id:
        type: string
        description: >-
          The externally-provided ID of the customer for whom to list credit
          cards.
      merchant_id:
        type: string
        description: The ID of the merchant for whom to list credit cards.
      payer_id:
        type: string
        description: >-
          A unique ID that you can assign and track when you vault a credit card
          or use a vaulted credit card to make a payment. This ID can help to
          avoid unintentional use or misuse of credit cards. Can be any value,
          such as a UUID, user name, or email address. This is being deprecated
          in favor of the external_customer_id property.
      external_card_id:
        type: string
        description: The externally-provided ID of the credit card.
    type: object
  CreditCardList:
    properties:
      items:
        type: array
        description: >-
          A vaulted credit card. To fund a payment, use the ID of the vaulted
          card.
        items:
          $ref: '#/definitions/CreditCard'
      links:
        type: array
        description: HATEOAS links related to this call.
        items:
          $ref: '#/definitions/Link'
      total_items:
        type: integer
        format: int64
        description: The total number of items.
      total_pages:
        type: integer
        format: int64
        description: The total number of pages.
    type: object
  JsonPatch:
    properties:
      op:
        type: string
        description: The operation to perform.
        enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
      path:
        type: string
        description: >-
          A JSON pointer. References a location in the target document where the
          operation is performed.
      value:
        type: string
        description: The value to apply. The remove operation does not require a value.
      from:
        type: string
        description: >-
          A JSON pointer. References the location in the target document from
          which to move the value. Required for the move operation.
    type: object
  JsonPatchRequest:
    properties:
      items:
        type: array
        description: >-
          A JSON patch object that you can use to apply partial updates to
          resources.
        items:
          $ref: '#/definitions/JsonPatch'
    type: object
  Link:
    properties:
      href:
        type: string
        description: >-
          The URL of the related HATEOAS link that you can use for subsequent
          calls.
      rel:
        type: string
        description: >-
          The link relationship. Describes how this link relates to the previous
          call. For example, use a self link to show details for the current
          call. Use a parent_payment link to show details for the parent
          payment. The rel value can also be a related call, such as execute or
          refund.
      method:
        type: string
        description: The HTTP method required to make the related call.
    type: object
